
INSERT INTO TYPE VALUES(default,'Area',FALSE);
INSERT INTO TYPE VALUES(default ,'Length',FALSE);
INSERT INTO TYPE VALUES(default ,'Volume',FALSE);
INSERT INTO TYPE VALUES(default ,'Mass',FALSE);
INSERT INTO TYPE VALUES(default ,'Temperature',TRUE);


INSERT INTO UNIT VALUES(default ,'Metre','Metric',2);
INSERT INTO UNIT VALUES(default ,'Yard','Imperial',2);
INSERT INTO UNIT VALUES(default ,'Kilogram','Metric',4);
INSERT INTO UNIT VALUES(default ,'Pound','Imperial',4);
INSERT INTO UNIT VALUES(default ,'Celsius','Metric',5);
INSERT INTO UNIT VALUES(default ,'Fahrenheit','Imperial',5);

INSERT INTO FACTORMAPPING VALUES(default ,1,2,1.09361);
INSERT INTO FACTORMAPPING VALUES(default ,2,1,0.9144027578);
INSERT INTO FACTORMAPPING VALUES(default ,3,4,2.20462);
INSERT INTO FACTORMAPPING VALUES(default ,4,3,0.4535929094);

INSERT INTO EXPRESSIONMAPPING VALUES(default ,5,6,'(i*1.8) + 32');
INSERT INTO EXPRESSIONMAPPING VALUES(default ,6,5,'(i-32) / 1.8');