-- INSERT 6 DATA FIXTURES
INSERT INTO TYPE (ID, NAME,EXPRESSION) VALUES (1, 'Area',false);
INSERT INTO TYPE (ID, NAME,EXPRESSION) VALUES (2, 'Length',false);
INSERT INTO TYPE (ID, NAME,EXPRESSION) VALUES (3, 'Volume',false);
INSERT INTO TYPE (ID, NAME,EXPRESSION) VALUES (4, 'Mass',false);
INSERT INTO TYPE (ID, NAME,EXPRESSION) VALUES (5, 'Temperature',false);
