-- INSERT 6 DATA FIXTURES
INSERT INTO UNIT (ID, NAME, SYSTEM,SYMBOL,TYPE) VALUES (1, 'Metre', 'Metric','m',2);
INSERT INTO UNIT (ID, NAME, SYSTEM,SYMBOL,TYPE) VALUES (2, 'Yard', 'Imperial','yd',2);
INSERT INTO UNIT (ID, NAME, SYSTEM,SYMBOL,TYPE) VALUES (3, 'Kilogram', 'Metric','kg',4);
INSERT INTO UNIT (ID, NAME, SYSTEM,SYMBOL,TYPE) VALUES (4, 'Pound', 'Imperial','lb',4);
INSERT INTO UNIT (ID, NAME, SYSTEM,SYMBOL,TYPE) VALUES (5, 'Celsius', 'Metric','C',5);
INSERT INTO UNIT (ID, NAME, SYSTEM,SYMBOL,TYPE) VALUES (6, 'Fahrenheit', 'Imperial','F',5);
